version: '3.8'

services:
  php-cli:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./app:/app
    working_dir: /app
    entrypoint: ["php"]
    stdin_open: true
    tty: true